### ISSUE TITLE
Remove detect_odr_violation=0 from .travis.yml

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#12]
Haven't spent time investigating this yet, but would be nice to pull out

**Comment by unicornss** [comment]
Additional context:
`$ ./tst/webrtc_client_test

=================================================================

==10056==ERROR: AddressSanitizer: odr-violation (0x000000937fe0):

  [1] size=8 'globalMemAlloc' /home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-pic/src/utils/src/Allocators.c:39:10

  [2] size=8 'globalMemAlloc' /home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-pic/src/utils/src/Allocators.c:39:10

These globals were registered at these points:

  [1]:

    #0 0x4a9d8e in __asan_register_globals /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_globals.cc:359:3

    #1 0x7f17c2fed93d in asan.module_ctor (/home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/build/libkvsWebrtcClient.so+0xc293d)

  [2]:

    #0 0x4a9d8e in __asan_register_globals /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_globals.cc:359:3

    #1 0x7f17c2ce70ad in asan.module_ctor (/home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/build/libkvsWebrtcSignalingClient.so+0x3b0ad)`

**Comment by Sean-Der** [comment]
Moved to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/20
