### ISSUE TITLE
[bug] deadlock when TURN is on

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#165]
See the bt of these two threads
```
Thread 6 (Thread 0x7f3ad8b43700 (LWP 20818)):
#0  0x00007f3aecf7410d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f3aecf6d098 in __GI___pthread_mutex_lock (mutex=0x7f3ab8006270) at ../nptl/pthread_mutex_lock.c:113
#2  0x00007f3af01757ba in defaultLockMutex (mutex=139890171863664) at amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-pic/src/utils/src/Mutex.c:202
#3  0x00007f3af015ef9c in turnConnectionSendData (pTurnConnection=0x7f3ab8000b20, pBuf=0x7f3ad8b42260 "", bufLen=28, pDestIp=0x7f3ac8018014) at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/TurnConnection.c:551
#4  0x00007f3af015b214 in iceUtilsSendStunPacket (pStunPacket=0x55c886db3fd0, password=0x0, passwordLen=0, pDest=0x7f3ac8018014, pSocketConnection=0x7f3ab80062f0, pTurnConnection=0x7f3ab8000b20, useTurn=1)
    at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/IceUtils.c:157
#5  0x00007f3af0156a07 in iceAgentSendKeepAliveTimerCallback (timerId=3, currentTime=15803165393161839, customData=94319744328448) at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/IceAgent.c:1079
#6  0x00007f3af01785e2 in timerQueueExecutor (args=0x55c886d88240) at amazon-kinesis-video-streams-webrtc-sdk-c/open-source/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-pic/src/utils/src/TimerQueue.c:561
#7  0x00007f3aecf6a6db in start_thread (arg=0x7f3ad8b43700) at pthread_create.c:463
#8  0x00007f3aecc9388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
```
Thread 10 (Thread 0x7f3ad0b69700 (LWP 20840)):
#0  0x00007f3aecf7410d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f3aecf6d098 in __GI___pthread_mutex_lock (mutex=0x55c886db3d90) at ../nptl/pthread_mutex_lock.c:113
#2  0x00007f3af01757ba in defaultLockMutex (mutex=94319744335248) at amazon-kinesis-video-streams-webrtc-sdk-c/open-source/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-pic/src/utils/src/Mutex.c:202
#3  0x00007f3af01572ab in incomingDataHandler (customData=94319744328448, pSocketConnection=0x7f3ab80062f0, pBuffer=0x55c886da2294 "\200}@.", bufferLen=1316, pSrc=0x7f3ac8018070, pDest=0x0)
    at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/IceAgent.c:1303
#4  0x00007f3af015fbea in turnConnectionDeliverChannelData (pTurnConnection=0x7f3ab8000b20, pChannelMsg=0x55c886da2290 "@\001\005$\200}@.", channelMsgLen=1320) at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/TurnConnection.c:793
#5  0x00007f3af015d6a9 in turnConnectionIncomingDataHandler (customData=139890171841312, pSocketConnection=0x7f3ab80062f0, pBuffer=0x55c886da2290 "@\001\005$\200}@.", bufferLen=1320, pSrc=0x7f3ad0b689f0, pDest=0x0)
    at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/TurnConnection.c:156
#6  0x00007f3af0153733 in connectionListenerReceiveDataRoutine (arg=0x55c886da2250) at amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/ConnectionListener.c:317
#7  0x00007f3aecf6a6db in start_thread (arg=0x7f3ad0b69700) at pthread_create.c:463
#8  0x00007f3aecc9388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
Deadlock happens as:
1. `iceAgentSendKeepAliveTimerCallback` acquires `MUTEX_LOCK(pIceAgent->lock)` and calls `turnConnectionSendData`, then `turnConnectionSendData` attempts to acquire `MUTEX_LOCK(pTurnConnection->lock)`
2. `turnConnectionIncomingDataHandler` acquires `MUTEX_LOCK(pTurnConnection->lock)` and calls `incomingDataHandler`, then `incomingDataHandler` attempts to acquire `MUTEX_LOCK(pIceAgent->lock)`

I have a fix for my own experiment, love to come up a pull request if I could have more eyes on it, it's not easy for me to follow which functions assume mutex is already acquired.

```
diff --git a/src/source/Ice/TurnConnection.c b/src/source/Ice/TurnConnection.c
index ac5aa06..672b745 100644
--- a/src/source/Ice/TurnConnection.c
+++ b/src/source/Ice/TurnConnection.c
@@ -133,14 +133,9 @@ STATUS turnConnectionIncomingDataHandler(UINT64 customData, PSocketConnection pS
     STATUS retStatus = STATUS_SUCCESS;
     PTurnConnection pTurnConnection = (PTurnConnection) customData;
 
-    BOOL locked = FALSE;
-
     CHK(pTurnConnection != NULL && pSocketConnection != NULL, STATUS_NULL_ARG);
     CHK_WARN(bufferLen > 0 && pBuffer != NULL, retStatus, "Got empty buffer");
 
-    MUTEX_LOCK(pTurnConnection->lock);
-    locked = TRUE;
-
     if (IS_STUN_PACKET(pBuffer)) {
         if (STUN_PACKET_IS_TYPE_ERROR(pBuffer)) {
             CHK_STATUS(turnConnectionHandleStunError(pTurnConnection, pSocketConnection, pBuffer, bufferLen));
@@ -164,10 +159,6 @@ CleanUp:
 
     CHK_LOG_ERR_NV(retStatus);
 
-    if (locked) {
-        MUTEX_UNLOCK(pTurnConnection->lock);
-    }
-
     LEAVES();
     return retStatus;
 }
@@ -186,11 +177,14 @@ STATUS turnConnectionHandleStun(PTurnConnection pTurnConnection, PSocketConnecti
     UINT64 data;
     PTurnPeer pTurnPeer = NULL;
     UINT64 currentTime;
+    BOOL locked = FALSE;
 
     CHK(pTurnConnection != NULL && pSocketConnection != NULL, STATUS_NULL_ARG);
     CHK(pBuffer != NULL && bufferLen > 0, STATUS_INVALID_ARG);
     CHK(IS_STUN_PACKET(pBuffer) && !STUN_PACKET_IS_TYPE_ERROR(pBuffer), retStatus);
 
+    MUTEX_LOCK(pTurnConnection->lock);
+    locked = TRUE;
     currentTime = GETTIME();
     // only handling STUN response
     stunPacketType = (UINT16) getInt16(*((PUINT16) pBuffer));
@@ -294,6 +288,10 @@ CleanUp:
 
     CHK_LOG_ERR_NV(retStatus);
 
+    if (locked) {
+        MUTEX_UNLOCK(pTurnConnection->lock);
+    }
+
     if (pStunPacket != NULL) {
         freeStunPacket(&pStunPacket);
     }
@@ -311,11 +309,15 @@ STATUS turnConnectionHandleStunError(PTurnConnection pTurnConnection, PSocketCon
     PStunAttributeNonce pStunAttributeNonce = NULL;
     PStunAttributeRealm pStunAttributeRealm = NULL;
     PStunPacket pStunPacket = NULL;
+    BOOL locked = FALSE;
 
     CHK(pTurnConnection != NULL && pSocketConnection != NULL, STATUS_NULL_ARG);
     CHK(pBuffer != NULL && bufferLen > 0, STATUS_INVALID_ARG);
     CHK(STUN_PACKET_IS_TYPE_ERROR(pBuffer), retStatus);
 
+    MUTEX_LOCK(pTurnConnection->lock);
+    locked = TRUE;
+
     if (pTurnConnection->credentialObtained) {
         retStatus = deserializeStunPacket(pBuffer, bufferLen, pTurnConnection->longTermKey, MD5_DIGEST_LENGTH, &pStunPacket);
     }
@@ -380,6 +382,10 @@ CleanUp:
 
     CHK_LOG_ERR_NV(retStatus);
 
+    if (locked) {
+        MUTEX_UNLOCK(pTurnConnection->lock);
+    }
+
     if (pStunPacket != NULL) {
         freeStunPacket(&pStunPacket);
     }
@@ -393,6 +399,7 @@ STATUS turnConnectionHandleChannelDataTcpMode(PTurnConnection pTurnConnection, P
     UINT32 bytesToCopy = 0, remainingMsgSize = 0, paddedDataLen = 0, remainingBufLen = 0;
     PBYTE pCurPos = NULL;
     UINT32 i = 0;
+    BOOL locked = FALSE;
 
     CHK(pTurnConnection != NULL, STATUS_NULL_ARG);
     CHK(pBuffer != NULL && bufferLen > 0, STATUS_INVALID_ARG);
@@ -400,6 +407,8 @@ STATUS turnConnectionHandleChannelDataTcpMode(PTurnConnection pTurnConnection, P
     pCurPos = pBuffer;
     remainingBufLen = bufferLen;
     while(remainingBufLen > 0) {
+        MUTEX_LOCK(pTurnConnection->lock);
+        locked = TRUE;
         if (pTurnConnection->currRecvDataLen > 0) {
             if (pTurnConnection->currRecvDataLen >= TURN_DATA_CHANNEL_SEND_OVERHEAD) {
                 // pTurnConnection->recvDataBuffer always has channel data start
@@ -422,6 +431,8 @@ STATUS turnConnectionHandleChannelDataTcpMode(PTurnConnection pTurnConnection, P
                           "Should not store more than one channel data message in recvDataBuffer");
 
                 if (pTurnConnection->currRecvDataLen == (paddedDataLen + TURN_DATA_CHANNEL_SEND_OVERHEAD)) {
+                    MUTEX_UNLOCK(pTurnConnection->lock);
+                    locked = FALSE;
                     CHK_STATUS(turnConnectionDeliverChannelData(pTurnConnection,
                                                                 pTurnConnection->recvDataBuffer,
                                                                 pTurnConnection->currRecvDataLen));
@@ -440,6 +451,8 @@ STATUS turnConnectionHandleChannelDataTcpMode(PTurnConnection pTurnConnection, P
 
             paddedDataLen = ROUND_UP((UINT32) getInt16(*(PINT16) (pCurPos + SIZEOF(UINT16))), 4);
             if (remainingBufLen >= (paddedDataLen + TURN_DATA_CHANNEL_SEND_OVERHEAD)) {
+                MUTEX_UNLOCK(pTurnConnection->lock);
+                locked = FALSE;
                 CHK_STATUS(turnConnectionDeliverChannelData(pTurnConnection,
                                                             pCurPos,
                                                             paddedDataLen + TURN_DATA_CHANNEL_SEND_OVERHEAD));
@@ -456,12 +469,19 @@ STATUS turnConnectionHandleChannelDataTcpMode(PTurnConnection pTurnConnection, P
                 remainingBufLen = 0;
             }
         }
+        if (locked) {
+            MUTEX_UNLOCK(pTurnConnection->lock);
+        }
     }
 
 CleanUp:
 
     CHK_LOG_ERR_NV(retStatus);
 
+    if (locked) {
+        MUTEX_UNLOCK(pTurnConnection->lock);
+    }
+
     return retStatus;
 }
 
@@ -764,6 +784,7 @@ STATUS turnConnectionDeliverChannelData(PTurnConnection pTurnConnection, PBYTE p
     UINT64 data;
     PTurnPeer pTurnPeer = NULL;
     UINT32 paddedDataLen;
+    BOOL locked = FALSE;
 
     CHK(pTurnConnection != NULL, STATUS_NULL_ARG);
     CHK(pChannelMsg != NULL && channelMsgLen > 0, STATUS_INVALID_ARG);
@@ -781,6 +802,9 @@ STATUS turnConnectionDeliverChannelData(PTurnConnection pTurnConnection, PBYTE p
             channelMsgLen == paddedDataLen + TURN_DATA_CHANNEL_SEND_OVERHEAD, STATUS_INVALID_ARG);
     }
 
+    MUTEX_LOCK(pTurnConnection->lock);
+    locked = TRUE;
+
     CHK_STATUS(doubleListGetHeadNode(pTurnConnection->turnPeerList, &pCurNode));
     while (pCurNode != NULL) {
         CHK_STATUS(doubleListGetNodeData(pCurNode, &data));
@@ -788,6 +812,9 @@ STATUS turnConnectionDeliverChannelData(PTurnConnection pTurnConnection, PBYTE p
 
         pTurnPeer = (PTurnPeer) data;
         if (pTurnPeer->channelNumber == channelNumber) {
+            MUTEX_UNLOCK(pTurnConnection->lock);
+            locked = FALSE;
+
             DLOGV("data available from channel %u", channelNumber);
             if (pTurnConnection->turnConnectionCallbacks.applicationDataAvailableFn != NULL) {
                 pTurnConnection->turnConnectionCallbacks.applicationDataAvailableFn(
@@ -806,6 +833,10 @@ CleanUp:
 
     CHK_LOG_ERR_NV(retStatus);
 
+    if (locked) {
+        MUTEX_UNLOCK(pTurnConnection->lock);
+    }
+
     return retStatus;
 }
 
```

**Comment by MushMal** [comment]
@staowyze thanks for reporting! Give us a short while to go over the issue and the proposed solution. I will make sure to loop you in shortly.

**Comment by MushMal** [comment]
Looking at the design, there is indeed a potential for a deadlock. The changes you are proposing will change the timing but will not fundamentally fix the issue. We are working on the fix. Will pull you in onto a PR once we get it out.

**Comment by staowyze** [comment]
Looking forward to having it, thank you.

**Comment by MushMal** [comment]
Pushed a PR: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/166

For some reason I am unable to add you as a reviewer. At any rate, please see if you can make comments.

**Comment by MushMal** [comment]
@staowyze the PR is in master now. Would you be so kind to check that out?

**Comment by staowyze** [comment]
@MushMal thank you for the quick response, drop a couple of comments on your PR, please take a look.

**Comment by staowyze** [comment]
fix is in master, close for now, impressed by the team.

**Comment by MushMal** [comment]
Attempting to target fix interlocking in the ICE agent instead of spinning up a thread for the turn connection which is more logical in terms of layering but far more expensive. @staowyze - could you take a look?

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/168 regarding previous comment ^^
